# Generated by Django 4.1.7 on 2023-02-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0005_tag_alter_cso_managers_alter_designer_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='VendorService',
        ),
    ]
