# Generated by Django 4.1.7 on 2023-02-18 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_service_task_vendor_vendorservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact_no',
            field=models.CharField(help_text='e.g. 01712345678', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^0[0-9]{10}$')], verbose_name='contact number'),
        ),
    ]
